spring:
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      fail-fast: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 3000
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000
    consumer:
      group-id: student-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

kafka:
  embedded:
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-security: true

logging:
  level:
    com.example.demo.message: debug
    org.apache.kafka: error
    kafka.server: error
    kafka.network: error
    org.apache.kafka.clients.NetworkClient: error